assume_extension: true
check_external_hash: true
check_favicon: true
check_html: true
check_img_http: true
check_opengraph: true
disable_external: false
empty_alt_ignore: false
enforce_https: true
file_ignore:
  - ./docs/_site/vendor/
internal_domains:
  - 127.0.0.1:4000
  - localhost:4000
url_ignore:
  - /^mailto:/
  - /^tel:/
  - /^#/
  - https://github.com/mhenke/accelerate-devex-book-club-notebooklm/issues/new
url_swap:
  https://mhenke.github.io/accelerate-devex-book-club-notebooklm/: /