matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - script
      - style
  sources:
  - 'docs/**/*.md'
  - 'README.md'
  - 'docs/index.md'
  default_encoding: utf-8