title: Accelerate DevEx Book Club
description: A structured approach to implementing high-performing DevOps practices through &quot;Accelerate&quot; by Nicole Forsgren, Jez Humble, and Gene Kim
baseurl: '/accelerate-devex-book-club-notebooklm'
url: 'https://mhenke.github.io'

repository: mikehenke/accelerate-devex-book-club-notebooklm

# Theme
theme: minima

# Navigation
header_pages:
  - meetings.md
  - resources.md
  - prompts.md
  - feeds.md
  - transformation-complete.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Plugin settings
feed:
  excerpt_only: false

# Markdown settings
markdown: kramdown
highlighter: rouge

# Kramdown options
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  html_to_native: true
  # Force HTML5 output format (no self-closing tags)
  html5_output: true
  # Additional HTML5 settings
  parse_block_html: true
  parse_span_html: true
  html5: true

# Collections
collections:
  meetings:
    output: true
    permalink: /meetings/:name/
  resources:
    output: true
    permalink: /resources/:name/

# Defaults
defaults:
  - scope:
      path: ''
      type: 'meetings'
    values:
      layout: 'meeting'
  - scope:
      path: ''
      type: 'resources'
    values:
      layout: 'resource'
