title: Accelerate DevEx Book Club
description: A structured approach to implementing high-performing DevOps practices through &quot;Accelerate&quot; by Nicole Forsgren, Jez Humble, and Gene Kim
baseurl: "/accelerate-devex-book-club-notebooklm"
url: "https://mhenke.github.io"

# Theme
theme: minima

# Navigation
header_pages:
  - meetings.md
  - resources.md
  - prompts.md
  - feeds.md
  - transformation-complete.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Kramdown options
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  html_to_native: true

# Collections
collections:
  meetings:
    output: true
    permalink: /meetings/:name/
  resources:
    output: true
    permalink: /resources/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "meetings"
    values:
      layout: "meeting"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"