# GitHub Actions CI/CD Pipeline for Jekyll Site Testing
name: Jekyll Site Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd docs
          bundle install
          cd ..
          npm install

      - name: Build Jekyll site
        run: |
          cd docs
          bundle exec jekyll build --destination ../_site

      - name: HTML validation
        run: npx html-validate "_site/**/*.html"

      - name: CSS validation
        run: npx stylelint "docs/assets/**/*.scss" "docs/**/*.html"

      - name: Accessibility testing
        run: npx pa11y-ci --sitemap http://localhost:4000/sitemap.xml

      - name: JavaScript linting
        run: npx eslint "docs/**/*.{js,html}" --ext .js,.html

      - name: Link checking
        run: npx hyperlink "_site/**/*.html"

      - name: Install Playwright dependencies
        run: |
          cd tests
          npm install
          npx playwright install --with-deps

      - name: Start Jekyll server for testing
        run: |
          cd docs
          bundle exec jekyll serve --detach --port 4000
          sleep 5

      - name: Visual regression testing with Percy
        run: |
          cd tests
          npm run test:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Interactive component testing
        run: |
          cd tests
          npm run test:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
